[2024-07-08T01:01:27.073-0300] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: upload_multiple_csvs_to_s3_dag.upload_csv_to_s3 manual__2024-07-08T04:01:18.314881+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
